# Generated by Django 3.1 on 2020-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200824_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='datetime',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.IntegerField(default=0),
        ),
    ]
