# Generated by Django 3.1 on 2020-08-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20200824_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='datetime',
        ),
    ]
