# Generated by Django 3.1 on 2020-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200825_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='preorder',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='preorder',
            field=models.BooleanField(default=False),
        ),
    ]
