# Generated by Django 3.1 on 2020-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200812_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='single_malt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='blend',
            field=models.BooleanField(default=False),
        ),
    ]
