# Generated by Django 3.1 on 2020-08-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200812_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blend',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_release',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_malt',
            field=models.BooleanField(),
        ),
    ]
