# Generated by Django 3.1 on 2020-08-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200811_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerelease',
            name='pre_release',
            field=models.CharField(blank=True, default=False, max_length=254, null=True),
        ),
    ]
