# Generated by Django 3.1 on 2020-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200812_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blend',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='single_malt',
            field=models.CharField(max_length=50),
        ),
    ]
