# Generated by Django 3.1 on 2020-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200812_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='blend',
        ),
        migrations.AlterField(
            model_name='product',
            name='single_malt',
            field=models.BooleanField(default=True),
        ),
    ]
