# Generated by Django 3.1 on 2020-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200812_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='single_malt',
            field=models.BooleanField(default=False),
        ),
    ]
