# Generated by Django 3.1 on 2020-08-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200812_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='whisky_name',
        ),
    ]
