# Generated by Django 3.1 on 2020-08-13 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200813_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='whisky_name',
            new_name='name',
        ),
    ]
