# Generated by Django 3.1 on 2020-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200813_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pre_release',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
