# Generated by Django 3.1 on 2020-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200829_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
